"""
This family file was auto-generated by generate_family_file.py script.

Configuration parameters:
  url = https://nonsa.pl/wiki/Strona_g%C5%82%C3%B3wna
  name = nonsensopedia

"""
from abc import ABC

from pywikibot import family


class Nonsensopedia(family.Family, ABC):
    name = "nonsensopedia"
    langs = {'pl': 'nonsa.pl'}

    def scriptpath(self, code):
        return {'pl': ''}[code]

    def protocol(self, code):
        return {'pl': 'https'}[code]
